name: dcd_flut_notification
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.1.1
  http: ^1.0.0
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  timezone: ^0.9.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
